  CREATE TABLE "SEARCHAPP"."SUBSET" 
   ("SUBSET_ID" NUMBER NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1000) NOT NULL ENABLE, 
	"CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"CREATING_USER" VARCHAR2(200) NOT NULL ENABLE, 
	"PUBLIC_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"DELETED_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"QUERY_MASTER_ID_1" NUMBER NOT NULL ENABLE, 
	"QUERY_MASTER_ID_2" NUMBER, 
	"STUDY" VARCHAR2(200), 
	 CONSTRAINT "SUBSET_PK" PRIMARY KEY ("SUBSET_ID")
  USING INDEX COMPUTE STATISTICS 
  TABLESPACE "BIOMART"  ENABLE
   ) NOCOMPRESS NOLOGGING
  TABLESPACE "BIOMART" ;
  
  
  CREATE TABLE "SEARCHAPP"."REPORT" 
   ("REPORT_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(200), 
	"DESCRIPTION" VARCHAR2(1000), 
	"CREATINGUSER" VARCHAR2(200), 
	"PUBLIC_FLAG" CHAR(1), 
	"CREATE_DATE" TIMESTAMP (1), 
	"STUDY" VARCHAR2(200),
	"MODULE_NAME" varchar2(200)
   ) NOCOMPRESS NOLOGGING
  TABLESPACE "BIOMART" ;
  
   CREATE TABLE "SEARCHAPP"."REPORT_ITEM" 
   ("REPORT_ITEM_ID" NUMBER NOT NULL ENABLE, 
	"REPORT_ID" NUMBER NOT NULL ENABLE, 
	"CODE" VARCHAR2(4000)
   ) NOCOMPRESS NOLOGGING
  TABLESPACE "BIOMART" ;
  
CREATE OR REPLACE SYNONYM "BIOMART_USER"."SUBSET" FOR "SEARCHAPP"."SUBSET";
CREATE OR REPLACE SYNONYM "BIOMART_USER"."REPORT" FOR "SEARCHAPP"."REPORT";   
CREATE OR REPLACE SYNONYM "BIOMART_USER"."REPORT_ITEM" FOR "SEARCHAPP"."REPORT_ITEM";
  
